# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: people.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='people.proto',
  package='people',
  syntax='proto3',
  serialized_pb=_b('\n\x0cpeople.proto\x12\x06people\"\x14\n\x04Name\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x15\n\x06Number\x12\x0b\n\x03num\x18\x01 \x01(\t\"\x1a\n\x07\x43ompany\x12\x0f\n\x07\x63ompany\x18\x01 \x01(\t\"g\n\nPeopleInfo\x12\x1a\n\x04name\x18\x01 \x01(\x0b\x32\x0c.people.Name\x12\x1b\n\x03num\x18\x02 \x01(\x0b\x32\x0e.people.Number\x12 \n\x07\x63ompany\x18\x03 \x01(\x0b\x32\x0f.people.Company2\x82\x01\n\x0cPeopleSearch\x12\x34\n\x0e\x46indByFullName\x12\x0c.people.Name\x1a\x12.people.PeopleInfo\"\x00\x12<\n\x14\x46indByFirstCharacter\x12\x0c.people.Name\x1a\x12.people.PeopleInfo\"\x00\x30\x01\x42\x36\n\x1bio.grpc.examples.routeguideB\x0fRouteGuideProtoP\x01\xa2\x02\x03RTGb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_NAME = _descriptor.Descriptor(
  name='Name',
  full_name='people.Name',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='people.Name.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=44,
)


_NUMBER = _descriptor.Descriptor(
  name='Number',
  full_name='people.Number',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num', full_name='people.Number.num', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=67,
)


_COMPANY = _descriptor.Descriptor(
  name='Company',
  full_name='people.Company',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='company', full_name='people.Company.company', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=95,
)


_PEOPLEINFO = _descriptor.Descriptor(
  name='PeopleInfo',
  full_name='people.PeopleInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='people.PeopleInfo.name', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num', full_name='people.PeopleInfo.num', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='company', full_name='people.PeopleInfo.company', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=200,
)

_PEOPLEINFO.fields_by_name['name'].message_type = _NAME
_PEOPLEINFO.fields_by_name['num'].message_type = _NUMBER
_PEOPLEINFO.fields_by_name['company'].message_type = _COMPANY
DESCRIPTOR.message_types_by_name['Name'] = _NAME
DESCRIPTOR.message_types_by_name['Number'] = _NUMBER
DESCRIPTOR.message_types_by_name['Company'] = _COMPANY
DESCRIPTOR.message_types_by_name['PeopleInfo'] = _PEOPLEINFO

Name = _reflection.GeneratedProtocolMessageType('Name', (_message.Message,), dict(
  DESCRIPTOR = _NAME,
  __module__ = 'people_pb2'
  # @@protoc_insertion_point(class_scope:people.Name)
  ))
_sym_db.RegisterMessage(Name)

Number = _reflection.GeneratedProtocolMessageType('Number', (_message.Message,), dict(
  DESCRIPTOR = _NUMBER,
  __module__ = 'people_pb2'
  # @@protoc_insertion_point(class_scope:people.Number)
  ))
_sym_db.RegisterMessage(Number)

Company = _reflection.GeneratedProtocolMessageType('Company', (_message.Message,), dict(
  DESCRIPTOR = _COMPANY,
  __module__ = 'people_pb2'
  # @@protoc_insertion_point(class_scope:people.Company)
  ))
_sym_db.RegisterMessage(Company)

PeopleInfo = _reflection.GeneratedProtocolMessageType('PeopleInfo', (_message.Message,), dict(
  DESCRIPTOR = _PEOPLEINFO,
  __module__ = 'people_pb2'
  # @@protoc_insertion_point(class_scope:people.PeopleInfo)
  ))
_sym_db.RegisterMessage(PeopleInfo)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\033io.grpc.examples.routeguideB\017RouteGuideProtoP\001\242\002\003RTG'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces


  class PeopleSearchStub(object):

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.FindByFullName = channel.unary_unary(
          '/people.PeopleSearch/FindByFullName',
          request_serializer=Name.SerializeToString,
          response_deserializer=PeopleInfo.FromString,
          )
      self.FindByFirstCharacter = channel.unary_stream(
          '/people.PeopleSearch/FindByFirstCharacter',
          request_serializer=Name.SerializeToString,
          response_deserializer=PeopleInfo.FromString,
          )


  class PeopleSearchServicer(object):

    def FindByFullName(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def FindByFirstCharacter(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_PeopleSearchServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'FindByFullName': grpc.unary_unary_rpc_method_handler(
            servicer.FindByFullName,
            request_deserializer=Name.FromString,
            response_serializer=PeopleInfo.SerializeToString,
        ),
        'FindByFirstCharacter': grpc.unary_stream_rpc_method_handler(
            servicer.FindByFirstCharacter,
            request_deserializer=Name.FromString,
            response_serializer=PeopleInfo.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'people.PeopleSearch', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaPeopleSearchServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def FindByFullName(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def FindByFirstCharacter(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaPeopleSearchStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def FindByFullName(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    FindByFullName.future = None
    def FindByFirstCharacter(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()


  def beta_create_PeopleSearch_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('people.PeopleSearch', 'FindByFirstCharacter'): Name.FromString,
      ('people.PeopleSearch', 'FindByFullName'): Name.FromString,
    }
    response_serializers = {
      ('people.PeopleSearch', 'FindByFirstCharacter'): PeopleInfo.SerializeToString,
      ('people.PeopleSearch', 'FindByFullName'): PeopleInfo.SerializeToString,
    }
    method_implementations = {
      ('people.PeopleSearch', 'FindByFirstCharacter'): face_utilities.unary_stream_inline(servicer.FindByFirstCharacter),
      ('people.PeopleSearch', 'FindByFullName'): face_utilities.unary_unary_inline(servicer.FindByFullName),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_PeopleSearch_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('people.PeopleSearch', 'FindByFirstCharacter'): Name.SerializeToString,
      ('people.PeopleSearch', 'FindByFullName'): Name.SerializeToString,
    }
    response_deserializers = {
      ('people.PeopleSearch', 'FindByFirstCharacter'): PeopleInfo.FromString,
      ('people.PeopleSearch', 'FindByFullName'): PeopleInfo.FromString,
    }
    cardinalities = {
      'FindByFirstCharacter': cardinality.Cardinality.UNARY_STREAM,
      'FindByFullName': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'people.PeopleSearch', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
